77 profile match history mobile responsiveness
erin-fitzpatric/next-aom-stats pull request #110
Opened 2024-09-21 15:43 UTC by skspade

Hoping to have an a simple and easy win here. 

- Increases the break point into mobile layout for xl screens instead of md screens
- also wrapped fetch functions into useCallbacks and added them to the deps array to calm the "missing deps" warning

2024-09-21 18:23 UTC, erin-fitzpatric requested changes
I'm nervous this might be breaking to "mobile" view too easily. It might be that the layout just needs to be redesigned. This is at half size on my desktop, and probably similar to many laptops:
![image](https://github.com/user-attachments/assets/6dfc3d64-38c8-4ed1-842f-753be604fed4)

2024-09-22 03:56 UTC, erin-fitzpatric commented on src/middleware.ts
Does this middleware get applied to all routes? I want the profile stats to update in "like real time" aka the 3 minutes that we check the leaderboard API. Players check these after their games so they need to update ASAP.

2024-09-22 21:37 UTC, erin-fitzpatric commented
![image](https://github.com/user-attachments/assets/7d6d42e8-116c-436b-a97e-55ce0cefe9ef)

2024-09-28 06:55 UTC, skspade commented
![localhost_3000_profile_1073800087 Overview (2024-09-28 06 54 18)](https://github.com/user-attachments/assets/ece23dc4-f688-4a4d-a00a-a2a956f0b4bb)
![localhost_3000_profile_1073800087 Overview (2024-09-28 06 54 33)](https://github.com/user-attachments/assets/3033e183-fae7-4504-8df3-b036dc93bb6c)

2024-09-28 07:10 UTC, erin-fitzpatric commented
LOVE IT

2024-09-28 19:19 UTC, erin-fitzpatric approved these changes

2024-09-28 19:19 UTC, merged