add user profile stats by god
erin-fitzpatric/next-aom-stats pull request #115
Opened 2024-09-24 07:38 UTC by cishiv

Changes:

- Adds `/api/data/builds` and `/api/data/game_modes` (avoids us having to maintain hard-coded values, and has the upshot of having the `game_modes` list used in the filter only include `game_modes` that have been played) - added cache control headers to this so we don't overfetch on each page reload.
- Adds `/api/stats/users/gods` + service
- Adds `majorGodNameToIndex` function
- Adds the `playerGodStats.tsx` component

How it works:
- We use the `Matches` collection and Mongo filters to pull back the appropriate Match info (all matches for a provided profileId, with some combination of civ, patch and major god) - we then manipulate the returned data to get w/l and play rates, combined across game modes.
- I also opted **not** to centralise the fetch logic in `profile.tsx` (like the other components), it looked pretty monolithic already.

How it looks:
![Screenshot 2024-09-24 at 09 27 57](https://github.com/user-attachments/assets/2c46632a-ba95-4f1e-bb84-7e0948e769c6)

Extensions:
- I'd probably add a "Frequently Played" table in the future, but didn't want this PR to be too big as it's already getting big.

2024-09-24 16:55 UTC, erin-fitzpatric commented
This looks really good, I think play rate might be bugged though?
![image](https://github.com/user-attachments/assets/fe511d06-2f10-44f4-b077-a2c065a92429)

2024-09-24 17:06 UTC, erin-fitzpatric requested changes
Thanks for adding the builds and game_modes routes. I'm ok with it since there is a cache. I am slightly concerned about how well this will scale - we will eventually have 1 million + matches. Does it really make sense to scan this whole collection to find a game mode? 

Thanks for pulling the fetch logic out of profile.tsx - there's a lot of bloat due to some of the velocity of which we have been iterating, but this is definitely how it should be done long term.

I love the frequently played players feature if you want to pick that up next. I also would like a timeline to show change in rank over time.

@skspade - take a look at these changes for when you work on your profile styling overhaul PR again.

If you can fix the play %, I'll got ahead ad merge this.

2024-09-24 17:08 UTC, erin-fitzpatric commented on src/app/api/stats/user/gods/route.ts
I like how you organized this. Will be nice to keep "user" stat queries grouped together in the `stats/user` directory.

2024-09-24 19:09 UTC, cishiv commented
> This looks really good, I think play rate might be bugged though? ![image](https://private-user-images.githubusercontent.com/46466305/370382048-fe511d06-2f10-44f4-b077-a2c065a92429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMDUyMjcsIm5iZiI6MTcyNzIwNDkyNywicGF0aCI6Ii80NjQ2NjMwNS8zNzAzODIwNDgtZmU1MTFkMDYtMmYxMC00NGY0LWIwNzctYTJjMDY1YTkyNDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE5MDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYTQzZjMzZWI2YWYxYTBkNGI2ODUzMmE1YjJiZjhkNmYzYzAyNzEyY2JjMjI2Y2RiZWY2MzlkYzc5MTgzZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D674QHPjzlzyTmn5PyiY31xhrOCyqAIDf-r7ZSb3-qk)

Ah good catch, will take a look after work tomorrow.

2024-09-24 19:11 UTC, cishiv commented
> Thanks for adding the builds and game_modes routes. I'm ok with it since there is a cache. I am slightly concerned about how well this will scale - we will eventually have 1 million + matches. Does it really make sense to scan this whole collection to find a game mode?

Fair callout on the scalability - I think at 1M+ matches we'd probably want indexes on a couple of the fields (like profile_id) which would reduce the search space for distinct. We could also just use the hard coded match types tbh - it's not _that_ much of a UX loss.

2024-09-25 05:57 UTC, erin-fitzpatric commented
Looking forward to getting this out there! Let me know once you have made the above updates and I'll merge it in. Have a few other pressing front end stories I could use help with too if you want to dig into the stats pages 👀

2024-09-25 16:41 UTC, cishiv commented
@erin-fitzpatric looked into the play rate issue.

It's _technically_ not a bug. If you filter by a single god, the returned data will give you the play rate of that god out of all the results (which in this case, is just that god). Do you want it to be an absolute play rate? Would be a small change (e.g. if you filter by a specific god, give the play rate for that god out of all the gods). Just want to confirm if thats the behaviour you want.

2024-09-25 16:44 UTC, erin-fitzpatric commented
> @erin-fitzpatric looked into the play rate issue.
> 
> It's _technically_ not a bug. If you filter by a single god, the returned data will give you the play rate of that god out of all the results (which in this case, is just that god). Do you want it to be an absolute play rate? Would be a small change (e.g. if you filter by a specific god, give the play rate for that god out of all the gods). Just want to confirm if thats the behaviour you want.

Ya I don't think it is useful to have 100% showing for every god. I would expect it to be the percentage I have played that civ compared to other picks.

2024-09-25 16:50 UTC, cishiv commented
Okay cool - good sanity check. I've pushed the updated code.

No filters:
![image](https://github.com/user-attachments/assets/1da0d7c6-fc9f-4c96-b2be-999814c69c05)

Filter by god:
![image](https://github.com/user-attachments/assets/4f6c9201-95b0-4095-8593-84a4beed6deb)

I'll do a performance tuning pass if I make more changes to this code in different PRs.

2024-09-25 17:33 UTC, erin-fitzpatric commented
This looks awesome, thanks for your work! I was going to go ahead and merge this if you feel good about it. 

Would be awesome to get some timeline graphs for player elo over time and other stuff like that if you would be interested. I also need some major help in the stats sections. I have greyed out options for "map" and "matchup" stats that I would like to get out there.

2024-09-25 18:55 UTC, erin-fitzpatric approved these changes

2024-09-25 18:55 UTC, merged