Profile rating
erin-fitzpatric/next-aom-stats pull request #146
Opened 2024-10-01 06:23 UTC by prateeksingh19

2024-10-01 06:43 UTC, erin-fitzpatric requested changes
Look really good! Just some technical refactoring:

- move all of this to a SSR pattern in the `/service` directory instead of an API route
  - create a controller which will pretty much just call the service
  - create a service (where all of this logic will go)
 
Make sure the function can accept gameMode as a param so 1v1 isn't hard coded, and also include an optional `startDate` and `endDate`. Allows for filters by weeks, months, years over time. If these are passed, add them to the `find`

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +      gameMode: "1V1_SUPREMACY",
Make this dynamic for the gameMode passed in the request.

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +  const pathSegments = url.pathname.split("/");
Look at the other examples to get the req params in a similar manner.

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +}
Let's utilize server side rendering for this. Instead of making a route in the API folder, create a typescript file with "user server" at the top. You would then call it like a regular function without the need to make a request. You should make two files in the `/server` directory:
- a controller
- a service

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +      [`matchHistoryMap.${profileId}`]: { $exists: true },
clever, I like it! You could also do an aggregation pipeline, but this works.

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +          });
create a mapper function for this

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +      return Response.json(allNewRatings);
type your new server side rendered function to return a number[] as you have declared already up above.

2024-10-01 06:43 UTC, erin-fitzpatric commented on src/app/api/profileRating/[profile_id]/route.ts
> +      throw new Error(`No data found for profile ID: ${profileId}`);
Think about what the front end should display if this error is thrown.

2024-10-01 08:46 UTC, prateeksingh19 commented on src/app/api/profileRating/[profile_id]/route.ts
> +      gameMode: "1V1_SUPREMACY",
Done

2024-10-01 08:48 UTC, prateeksingh19 commented on src/app/api/profileRating/[profile_id]/route.ts
> +  const pathSegments = url.pathname.split("/");
Done

2024-10-01 09:02 UTC, prateeksingh19 commented on src/app/api/profileRating/[profile_id]/route.ts
> +      [`matchHistoryMap.${profileId}`]: { $exists: true },
Done

2024-10-01 09:07 UTC, prateeksingh19 commented on src/app/api/profileRating/[profile_id]/route.ts
> +          });
Created an aggregation function so removed this

2024-10-03 02:49 UTC, erin-fitzpatric requested changes
Looks like a great start! Please revise the state variables as well as the fetch function as I suggested.

Front end looks to still be a work in progress, let me know when you are ready for feedback on the UI. The line graph component looks pretty cool - will need some styling and labels on the x & y axis.

2024-10-03 02:49 UTC, erin-fitzpatric commented on src/components/profile/profile.tsx
> +        setChartData2v2(chartData2v2_3v3);
I don't think you need separate state variables here. Instead do something like
```
const [ chartData, setChartData] = useState<ChartData>(
  {
    1v1: yourData
    2v2: yourData
  {
)
```

2024-10-03 02:49 UTC, erin-fitzpatric commented on src/server/controllers/profile-rating.ts
> +}: MatchParams): Promise<{ chartData1v1: any; chartData2v2_3v3: any }> {
Please add types for chartData. Return an object like what I commented above.

2024-10-03 02:49 UTC, erin-fitzpatric commented on src/server/services/profile-rating-service.ts
> +  );
You should be able to make a single request to the DB instead of two with some fancy pipeline aggregate work. Burbl should be able to help you with this if you get stuck...he's worked with making some pretty complex pipelines.

2024-10-03 02:49 UTC, erin-fitzpatric commented on src/server/services/profile-rating-service.ts
> +  );
Break this mapping logic down into a mapping function(s) after you update the mongo call.

2024-10-03 02:49 UTC, erin-fitzpatric commented on src/middleware.ts
> +  if (process.env.NODE_ENV == "development") {
Did you mean to change this?

2024-10-03 06:23 UTC, prateeksingh19 commented on src/middleware.ts
> +  if (process.env.NODE_ENV == "development") {
Yes, it was showing cache data only when i was building backend, i had to restart the server in order to view the latest data. Now, the backend work is almost complete, I'll revert it once i complete this PR.

2024-10-07 08:50 UTC, prateeksingh19 commented on src/components/profile/profile.tsx
> +        setChartData2v2(chartData2v2_3v3);
done

2024-10-07 08:57 UTC, prateeksingh19 commented on src/server/controllers/profile-rating.ts
> +}: MatchParams): Promise<{ chartData1v1: any; chartData2v2_3v3: any }> {
done

2024-10-09 04:26 UTC, erin-fitzpatric requested changes
![image](https://github.com/user-attachments/assets/2efc3943-6b55-4b4b-bc70-64ca4a225a87)

WOW! Looks really good. A few things to cleanup:
- can both lines have the white data points?
- if a player does not have a 1v1 or team game, hide that line
- I played games tonight but my profile rating does not reflect my most recent games, why is that? I have a game on 10/8.
![image](https://github.com/user-attachments/assets/f5a8c213-2168-4ddd-82e8-d709fcfd7ef7)

Please add axis labels. I prefer Sep 23, Oct 4, etc. 
![image](https://github.com/user-attachments/assets/7922ae4c-2181-4db0-a6b2-9d929484599c)

2024-10-09 04:26 UTC, erin-fitzpatric commented on src/components/profile/playerInfo.tsx
> +  });
Thanks for updating this state object, this looks great!

2024-10-09 06:03 UTC, erin-fitzpatric commented
@skspade - please give this a review when you get a chance. Taking a final pass on cleaning up the code.

2024-10-10 02:17 UTC, erin-fitzpatric requested changes

2024-10-10 02:17 UTC, erin-fitzpatric commented on src/middleware.ts
> +  if (process.env.NODE_ENV == "development") {
I think this needs to be reverted

2024-10-10 22:20 UTC, skspade commented
> @skspade - please give this a review when you get a chance. Taking a final pass on cleaning up the code.

Yes! I'll look at this tonight

2024-10-11 14:18 UTC, skspade approved these changes
Looks great to me! I don't think I would have done it any differently

2024-10-11 14:37 UTC, erin-fitzpatric approved these changes

2024-10-11 14:37 UTC, merged